alibaba:
  cloud:
      access-key: LTAI5tGBEGwLrxLUiERYyrwC
      secret-key: Nczkx97CgudbUzpaCfRlugSfKHTZfe
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-giantjason

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party

server:
  port: 30000